"""Raw data quality exploration - run once to understand what we're dealing with."""
import pandas as pd
import numpy as np

pd.set_option("display.width", 160)
pd.set_option("display.max_columns", 50)

emp = pd.read_csv("employees.csv", parse_dates=["hire_date", "exit_date"])
attr = pd.read_csv("attrition_log.csv", parse_dates=["exit_date"])
eng = pd.read_csv("engagement.csv", parse_dates=["survey_date"])
perf = pd.read_csv("performance.csv", parse_dates=["review_date"])

print("=" * 80)
print("EMPLOYEES.csv shape:", emp.shape)
print(emp.dtypes)
print("\nNulls per column:\n", emp.isnull().sum())
print("\nstatus counts:\n", emp["status"].value_counts())
print("\ndepartment counts:\n", emp["department"].value_counts())
print("\nrole_family counts:\n", emp["role_family"].value_counts())
print("\nrole_level counts:\n", emp["role_level"].value_counts().sort_index())
print("\ncontract_type counts:\n", emp["contract_type"].value_counts())
print("\nhire_source counts:\n", emp["hire_source"].value_counts())
print("\nlegacy_entity_code counts:\n", emp["legacy_entity_code"].value_counts())
print("\ndata_source_system counts:\n", emp["data_source_system"].value_counts())
print("\ngender counts:\n", emp["gender"].value_counts())
print("\nage_band counts:\n", emp["age_band"].value_counts())
print("\nhipo_flag counts:\n", emp["hipo_flag"].value_counts())
print("\nacting_appointment counts:\n", emp["acting_appointment"].value_counts())
print("\npromotion_eligible counts:\n", emp["promotion_eligible"].value_counts())
print("\nhire_date range:", emp["hire_date"].min(), emp["hire_date"].max())
print("exit_date range:", emp["exit_date"].min(), emp["exit_date"].max())
print("\nsalary describe:\n", emp["salary"].describe())
print("\ncompa_ratio describe:\n", emp["compa_ratio"].describe())
print("\ntenure_months describe:\n", emp["tenure_months"].describe())
print("\ndays_to_fill describe:\n", emp["days_to_fill"].describe())
print("\ndays_to_fill nulls by hire_source:\n", emp.groupby("hire_source")["days_to_fill"].apply(lambda s: s.isnull().mean()))

# status vs exit_date consistency
print("\nactive with exit_date set:", ((emp.status == "active") & emp.exit_date.notnull()).sum())
print("departed with exit_date null:", ((emp.status == "departed") & emp.exit_date.isnull()).sum())

print("\nduplicated employee_id:", emp["employee_id"].duplicated().sum())

print("=" * 80)
print("ATTRITION_LOG.csv shape:", attr.shape)
print(attr.dtypes)
print("\nNulls:\n", attr.isnull().sum())
print("\nexit_type counts:\n", attr["exit_type"].value_counts())
print("\nregrettable_flag counts:\n", attr["regrettable_flag"].value_counts())
print("\npathway counts:\n", attr["pathway"].value_counts())
print("\ncrosstab exit_type x pathway:\n", pd.crosstab(attr.exit_type, attr.pathway))
print("\ncrosstab exit_type x regrettable_flag:\n", pd.crosstab(attr.exit_type, attr.regrettable_flag))
print("\nstated_exit_reason counts:\n", attr["stated_exit_reason"].value_counts())
print("\nperformance_band_at_exit counts:\n", attr["performance_band_at_exit"].value_counts())
print("\nnotice_period_served counts:\n", attr["notice_period_served"].value_counts())
print("\nduplicated employee_id in attrition_log:", attr["employee_id"].duplicated().sum())

# Does every departed employee in employees.csv have an attrition_log row?
departed_ids = set(emp.loc[emp.status == "departed", "employee_id"])
attr_ids = set(attr["employee_id"])
print("\ndeparted in employees.csv:", len(departed_ids))
print("rows in attrition_log:", len(attr_ids))
print("departed but missing from attrition_log:", len(departed_ids - attr_ids))
print("in attrition_log but not marked departed in employees.csv:", len(attr_ids - departed_ids))

print("=" * 80)
print("ENGAGEMENT.csv shape:", eng.shape)
print(eng.dtypes)
print("\nNulls:\n", eng.isnull().sum())
print("\nwave_number counts:\n", eng["wave_number"].value_counts().sort_index())
print("\nresponse_flag counts:\n", eng["response_flag"].value_counts())
print("\nresponse rate by wave:\n", eng.groupby("wave_number")["response_flag"].mean())
print("\nsurvey_date range per wave:\n", eng.groupby("wave_number")["survey_date"].agg(["min", "max"]))
print("\nrows per employee (waves issued) describe:\n", eng.groupby("employee_id").size().describe())
print("\nemployees with 0 rows in engagement:", emp.shape[0] - eng["employee_id"].nunique())

print("=" * 80)
print("PERFORMANCE.csv shape:", perf.shape)
print(perf.dtypes)
print("\nNulls:\n", perf.isnull().sum())
print("\nperformance_rating counts:\n", perf["performance_rating"].value_counts())
print("\nreview_cycle counts:\n", perf["review_cycle"].value_counts())
print("\npromotion_recommendation counts:\n", perf["promotion_recommendation"].value_counts())
print("\ngoal_achievement_score describe:\n", perf["goal_achievement_score"].describe())
print("\nrows per employee describe:\n", perf.groupby("employee_id").size().describe())
